<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Search' => '搜索',
  'Reset' => '重置',
  'Update' => '更新',
  'Delete' => '删除',
  'Name' => '名称',
  'Create' => '创建',
  'Save' => '保存',
  'Position' => '排序',
  'Type' => '类型',
  'Create {modelClass}' => '创建 {modelClass}',
  'Update {modelClass}' => '更新 {modelClass}',
  'Created By' => '创建者',
  'Updated By' => '更新者',
  'Created At' => '创建时间',
  'Updated At' => '更新时间',

  //time
  'Years' => ' 年 ',
  'Months' => ' 个月 ',
  'Weeks' => ' 星期 ',
  'Days' => ' 天 ',
  'Hours' => ' 小时 ',
  'Minutes' => ' 分钟 ',
  'Seconds' => ' 秒 ',
  'ago' => ' 前',

  //tips
  'Invalid request' => '无效请求',
  'save success!' => '保存成功！',
  
  //index
  'You are not allowed to access this page.' => '你未被允许访问此页',
  'Hello, {username}!' => '你好, {username}!',
  'Home' => '主页',
  'Frontend Home' => '前端首页',
  'Dashboards' => '控制面板',
  'Login' => '登录',
  'Logout' => '退出',
  'choose language' => '选择语言',
  'Overview' => '概览',
  'Site Home' => '网站首页',
  'Hello,welcome to use DCMS!' => '你好，欢迎使用DCMS！',
  'Settings' => '设置',
  'Users' => '用户',
  'Category' => '分类',
  'Comments' => '评论',
  'Lookup' => '映射',
  'Sources' => '来源',
  'Writers' => '编辑',
  'Signup' => '注册',
  'Tags' => '标签',
  'Links' => '链接',
  'Articles' => '文章',
  'Posts' => '文章',
  'Page' => '单页',
  'Navs' => '导航',

  //Site
  'Site name' => '网站名称',
  'Site url' => '网站URL',
  'Site title' => '网站标题',
  'Site keywords' => '网站关键字',
  'Site description' => '网站介绍',
  'Admin email' => '管理员邮箱',
  'Site copyright' => '网站版权',
  'stat code' => '统计代码',
  'Site closed' => '关闭网站',
  'close' => '关闭',
  'open' => '开启',
  'Site Info' => '网站信息',
  'Backend Access' => '后台访问',
  'Website was temporarily in closed.' => '网站暂时关闭',
  "You must add yourself ip to the list!" => '必须添加自己的ip到列表！',
  "Allow IP List to access the backend" => '允许访问后台的 IP 列表',
  'Above is a whitelist, example:<br>127.0.0.1 <br>113.139.20. * <br>Leave blank for all accessible IP<br><p class="text-info">Current ip: {ip}</p>' => '上面是一个白名单列表，范例：<br>127.0.0.1<br>113.139.20.*<br>留空为所有IP均可访问<br><p class="text-info">当前ip：{ip}</p>',
  'Allow Signup' => '允许注册',
  'Closed Signup display message' => '关闭注册时显示信息',
  'Signup Verify Way' => '注册验证方式',
  'Normal' => '正常',
  'Approve' => '人工审核',
  'Verify By Email' => '通过邮箱验证',
  'Hold User Name' => '保留的用户名',
  'Site closed display message' => '网站关闭时显示的信息',

  //category
  'Categories' => '分类',
  'Create Category' => '创建分类',
  'Categories Tree' => '分类树',
  'Please select the parent node' => '请选择父分类',
  'Update Category: ' => '更新分类：',
  'Summary' => '简介',
  'Parent' => '父分类',
  'uncategorized' => '未分类',

  //lookup
  'Code' => '代码',
  'Slides' => '幻灯',
  'Headline' => '头条',
  'Recommend' => '推荐',
  'publish' => '发布',
  'draft' => '草稿',
  'pending' => '待审',

  //link
  'Link' => '链接',
  'Url' => '网址',
  'Logo' => '标识',
  'Target' => '打开方式',
  'Visible' => '是否显示',
  'Preview' => '预览',
  '_self' => '默认',
  '_blank' => '新窗口',
  'Available' => '显示',
  'Unavailable' => '不显示',
  '{file} files can not exceed 2MB. Please upload a small bit of the file.' => '{file} 文件不能超过 2MB. 请上传小一点儿的文件.',
  'Picture' => '图片',
  'Text' => '文字',

  //toggleColumn
  '"{attribute}" attribute cannot be empty.' => '{attribute}" 属性不能为空.',
  'Uncheck' => '未检验',
  'Check' => '校验',
  'Not set' => '没有设置',

  //post
  'Article' => '文章',
  'Category' => '分类',
  'Title' => '标题',
  'Content' => '内容',
  'Status' => '状态',
  'Please select the category' => '请选择分类',
  'Published' => '发布',
  'Draft' => '草稿',
  'Published At' => '发表于',
  'Disallow Comment' => '禁止评论',
  'Please select the Category' => '请选择分类',
  'Set It Now' => '设为当前时间',
  'Upload' => '上传',
  'Likes' => '喜欢次数',
  'Views' => '浏览次数',
  'Comment Count' => '评论次数',
  'Thumbnail' => '缩略图',
  'Type' => '类型',
  'Choose' => '选择',
  'Content' => '内容',

  // Comment
  'Author'=>'作者',

  //user
  'Username'=>'用户名',
  'User Email'=>'邮箱',
  'Password'=>'密码',
  'This username has already been taken.'=> '这个用户名已经被占用',
  'This email address has already been taken.'=>'这个邮箱地址已被占用',

  //
  'Navs Tree' => '导航树',
  'Create Nav' => '创建导航',
);
